service: website-check

provider:
  name: aws
  runtime: python3.8
  profile: macbook
  region: ap-southeast-2
  stage: ${env:stage, 'dev'}
  environment:
    sender: ${ssm:/website-check/sender} 
    recipient: ${ssm:/website-check/recipient}

plugins:
  - serverless-python-requirements
  - serverless-iam-roles-per-function
 
  
custom:
  pythonRequirements:
    dockerizePip: false


functions:
  myFunction:
    handler: handler.handler
    iamRoleStatements:
      - Effect: Allow
        Action:
          - ses:SendEmail
        Resource: "*"
    events:
      - schedule:
          rate: cron(0 */6 * * ? *) //every 6 hours lambda is invoked
          enabled: true
